https://wikidocs.net/45101 참고하시면 바로 이해됩니당!

#### 할일

- 텍스트를 단락으로 구분: 제가 빨리 해서 올려드릴게요!
- 특수문자, 필요없는 문자

- 맞춤법 검사 라이브러리: 유솔님
- 전치사 처리 // 형태소 토큰화 라이브러리 

- 어디까지 돌아가는지 체크: 지원님

- 다음주 수요일 모임
-----------------------

- 보고서(LSTM, RNN 모델, 파라미터 조정)
- 데모영상

In [1]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN, LSTM

import io
import pandas as pd

### text 불러오기

- 텍스트 정제
- 하나의 의미 단락으로 구분

In [62]:
filename = "total.txt"
with io.open(filename, encoding = "utf-8") as f:
    text = f.read()

In [78]:
sentence_list = []
for (idx, sen) in enumerate(text.split(".")):
    if (idx == int(len(text.split(".")) / 10)):
        break
    sentence_list.append(sen + ".")
    
for (idx, sen) in enumerate(sentence_list):
    sentence_list[idx] = sentence_list[idx].replace("\n", "")

In [79]:
print(sentence_list)

['\ufeff“따라오지 마세요!”비명인 듯 날카롭고 선명한 한마디와 함께, ‘빠아아앙─’하는 경적소리가 사방에 울려 퍼진다.', ' 보통 차량들보다도 묵직하고 시끄러운 그 경적소리는 덤프트럭이 내는 소리였다.', '나는 도로로 뛰쳐나왔다.', ' 으슥한 골목에서부터 뒤를 쫓아오는 수상쩍은 사람으로 인해 날듯이 달리며 도망치다가, 그 속도를 제어하지 못하고 큰길의 도로로 뛰어나와버린 것이다.', '쾅!죽음은 찰나였다.', ' 내 얼굴과 가슴, 배, 허벅지 등에 차가운 감촉이 와 닿았다.', ' 겨울이 가까워오는 가을날의 아스팔트가 지닌 온도였다.', ' 널브러져있노라니 내 온몸에서 피가 새어나가는 느낌이 들어왔고, 곧 내 몸이 빠르게 식어가는 것도 느껴졌다.', '주마등처럼 평범했던 나날들이 스쳐지나간다.', ' 마지막을 장식하는 건 내 가족들의 얼굴이었다.', ' 다정하신 부모님, 얄밉지만 나를 잘 챙겨주던 언니, 군대에 들어갔지만 휴가 나올 때마다 맛있는 거 하나씩은 사들고 집에 돌아오던 오빠.', '그들의 얼굴이 밤하늘에 떠오른 보름달처럼 내 머릿속에 두둥실 떠올랐다.', ' 곧 맞이하게 될 죽음을 한탄할 겨를조차 없었다.', ' 서서히 눈이 감기고, 의식은 흐려져만 갔다.', '그때 그 순간, 내 몸은 아스팔트보다도 차가웠다.', '10분 정도가 흘렀을까.', '여전히 우리의 천사님들은 내가 알아들을 수 없는 대화들을 나누느라 바빴다.', ' 나는 손목에 쇠고랑을 찬 채로, 침대 위에 널브러져 그런 둘의 모습을 눈동자만 개똥벌레마냥 데굴데굴 굴리며 구경할 수밖에 없었는데.', '대체 저게 무슨 얘기들이지? 아까와 마찬가지로, 나로서는 전혀 이해할 수 없는 내용들이었다.', '뭐, 이를 테면,“기억이 쉽게 돌아올 것 같지가 않아.', ' 역시 내 주치의를 부르는 편이 좋지 않을까?”“아니면 마법으로 강제로 깨우는 방법도 있긴 합니다만.', '”“그건 정신건강에 안 좋으니까.', ' 가뜩이나 지금도 안 좋아 보이는데, 다른 부작용이라도 생겨버렸다간 ”“ 듣

In [80]:
def check_sentence(sentence):
    if ((sentence.find("\"") != -1) | (sentence.find("“") != -1) | (sentence.find("”") != -1)):
        return (0)
    elif (sentence,find("”") )
    elif ((sentence.find("[") != -1) | (sentence.find("]") != -1)):
        return (0)
    elif ((sentence.find("(") != -1) | (sentence.find(")") != -1)):
        return (0)
    elif ((sentence.find("<") != -1) | (sentence.find(">") != -1)):
        return (0)
    elif ((sentence.find("「") != -1) | (sentence.find("」") != -1)):
        return (0)
    elif ((sentence.find("-") != -1) | (sentence.find("_") != -1)):
        return (0)
    elif ((sentence.find("*") != -1) | (sentence.find("~") != -1)):
        return (0)
    elif ((sentence.find("^") != -1) | (sentence.find("#") != -1)):
        return (0)
    elif (sentence.find("  ") != -1):
        return (0)
    elif ((sentence.find("??") != -1) | (sentence.find("!!") != -1)):
        return (0)
    elif (sentence.find(".") == -1):
        return (0)
    
    ‘
    else:
        return (1)

In [81]:
temp = ""
num = 0
maxi = 10
for (idx, sentence) in enumerate(sentence_list):
    if (check_sentence(sentence) == 0):
        continue
    else:
        temp += sentence
        num += 1
        if (num == maxi):
            temp += "\n\n"
            num = 0

In [82]:
print(temp)

 보통 차량들보다도 묵직하고 시끄러운 그 경적소리는 덤프트럭이 내는 소리였다.나는 도로로 뛰쳐나왔다. 으슥한 골목에서부터 뒤를 쫓아오는 수상쩍은 사람으로 인해 날듯이 달리며 도망치다가, 그 속도를 제어하지 못하고 큰길의 도로로 뛰어나와버린 것이다.쾅!죽음은 찰나였다. 내 얼굴과 가슴, 배, 허벅지 등에 차가운 감촉이 와 닿았다. 겨울이 가까워오는 가을날의 아스팔트가 지닌 온도였다. 널브러져있노라니 내 온몸에서 피가 새어나가는 느낌이 들어왔고, 곧 내 몸이 빠르게 식어가는 것도 느껴졌다.주마등처럼 평범했던 나날들이 스쳐지나간다. 마지막을 장식하는 건 내 가족들의 얼굴이었다. 다정하신 부모님, 얄밉지만 나를 잘 챙겨주던 언니, 군대에 들어갔지만 휴가 나올 때마다 맛있는 거 하나씩은 사들고 집에 돌아오던 오빠.

그들의 얼굴이 밤하늘에 떠오른 보름달처럼 내 머릿속에 두둥실 떠올랐다. 곧 맞이하게 될 죽음을 한탄할 겨를조차 없었다. 서서히 눈이 감기고, 의식은 흐려져만 갔다.그때 그 순간, 내 몸은 아스팔트보다도 차가웠다.10분 정도가 흘렀을까.여전히 우리의 천사님들은 내가 알아들을 수 없는 대화들을 나누느라 바빴다. 나는 손목에 쇠고랑을 찬 채로, 침대 위에 널브러져 그런 둘의 모습을 눈동자만 개똥벌레마냥 데굴데굴 굴리며 구경할 수밖에 없었는데.대체 저게 무슨 얘기들이지? 아까와 마찬가지로, 나로서는 전혀 이해할 수 없는 내용들이었다.” 같은 대화내용들.뭐시라? 저기요.

 누구 씨의 움직이는 성에서 나올 법한 단발 천사님과 책벌레 금발 천사님, 지금 말 다했습니까? 예!?아까부터 자꾸 마법이니 어쩌니, 기억 상실이니 어쩌니 하는 대화를 나누고 있는 저 두 명의 천사자식, 이 아니라, 님들.아니, 저기요. 제 기억은 멀쩡하단 말입니다! 물론 내 정신건강도 댁들 걱정 따윈 필요 없을 만큼 멀쩡하고.대한민국에서 살아가던 고3을 앞둔 고2였다는 사실도, 내가 좋아했던 연예인도, 내가 좋아했던 혈통빨 눈깔대전 만화책도, 게임도, 또 우리 엄마랑 아빠, 언니랑 오빠들 얼굴도

In [83]:
text = temp

### 토큰화

- 문장을 쪼개 단어를 분리하고, 단어 각각에 대응하는 숫자를 부여

In [84]:
tk = Tokenizer()
tk.fit_on_texts([text])

print("단어의 개수:", len(tk.word_index))

단어의 개수: 13921


In [85]:
print(tk.word_index)

{'나는': 1, '내': 2, '그': 3, '내가': 4, '그런': 5, '있는': 6, '이': 7, '것': 8, '수': 9, '게': 10, '안': 11, '한': 12, '건': 13, '나를': 14, '이런': 15, '왜': 16, '듯': 17, '같은': 18, '저': 19, '없는': 20, '고개를': 21, '하는': 22, '내게': 23, '지금': 24, '하지만': 25, '무슨': 26, '더': 27, '뭐': 28, '할': 29, '있었다': 30, '나': 31, '걸': 32, '표정으로': 33, '루이스가': 34, '잘': 35, '바로': 36, '말이다': 37, '대체': 38, '그의': 39, '그리고': 40, '우리': 41, '다른': 42, '이내': 43, '너무': 44, '거': 45, '그래': 46, '하고': 47, '되는': 48, '될': 49, '물론': 50, '말을': 51, '아닌': 52, '아니': 53, '나도': 54, '”': 55, '아니라': 56, '꽤': 57, '것이다': 58, '두': 59, '좀': 60, '채': 61, '마법': 62, '마치': 63, '루이스의': 64, '류이의': 65, '다': 66, '거야': 67, '그가': 68, '위해': 69, '’하는': 70, '보니': 71, '말이야': 72, '것도': 73, '’라고': 74, '어떻게': 75, '저런': 76, '아닌가': 77, '나의': 78, '된': 79, '사실': 80, '때': 81, '그렇게': 82, '그런데': 83, '어쨌거나': 84, '같은데': 85, '건가': 86, '표정을': 87, '이렇게': 88, '있을': 89, '아': 90, '거지': 91, '모든': 92, '란': 93, '또': 94, '보면': 95, '못': 96, '없었다': 97, '나와': 98, '말이': 99, '그는': 100, '생각을': 101, 

### 인코딩, 훈련데이터 만들기

In [86]:
traindata = []

for phrase in text.split("\n"):
    
    #단락을 숫자리스트로
    ph_splited = tk.texts_to_sequences([phrase])[0]
    
    #훈련데이터 생성 후 traindata에 append
    for i in range(1, len(ph_splited)):
        temp = []
        for j in range(0, i + 1):
            temp.append(ph_splited[j])
        traindata.append(temp)

print(traindata)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [87]:
print("훈련데이터 크기: %d" % len(traindata))

훈련데이터 크기: 35332


### 패딩넣기

In [88]:
max_len = 0
for data in traindata:
    if (len(data) > max_len):
        max_len = len(data)

print("훈련데이터요소의 최대크기(패딩크기): %d" % max_len)

훈련데이터요소의 최대크기(패딩크기): 180


In [89]:
traindata = pad_sequences(traindata, maxlen = max_len, padding = "pre")

In [90]:
print(traindata)

[[   0    0    0 ...    0  457 3987]
 [   0    0    0 ...  457 3987 3988]
 [   0    0    0 ... 3987 3988 3989]
 ...
 [   0    0    0 ...  161  942  354]
 [   0    0    0 ...  942  354 2182]
 [   0    0    0 ...  354 2182  177]]


### x 데이터, y 데이터 만들기

In [91]:
traindata = np.array(traindata)
x = traindata[:, :max_len - 1]
y = traindata[:, max_len - 1]

In [92]:
print(x)

[[    0     0     0 ...     0     0   457]
 [    0     0     0 ...     0   457  3987]
 [    0     0     0 ...   457  3987  3988]
 ...
 [    0     0     0 ... 13921   161   942]
 [    0     0     0 ...   161   942   354]
 [    0     0     0 ...   942   354  2182]]


In [93]:
print(y)

[3987 3988 3989 ...  354 2182  177]


In [94]:
y = to_categorical(y, dtype = np.int64)

### 모델 만들기

In [95]:
size = len(tk.word_index) + 1

model = Sequential()
model.add(Embedding(size, 10, input_length = max_len - 1)) # 레이블을 분리하였으므로 이제 X의 길이는 5
model.add(SimpleRNN(32))
model.add(Dense(size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x, y, epochs = 100, verbose = 2, batch_size = 10)

Epoch 1/100
3534/3534 - 233s - loss: 9.2909 - accuracy: 0.0074
Epoch 2/100
3534/3534 - 207s - loss: 8.7305 - accuracy: 0.0084
Epoch 3/100
3534/3534 - 192s - loss: 8.4515 - accuracy: 0.0096
Epoch 4/100
3534/3534 - 186s - loss: 8.1118 - accuracy: 0.0121
Epoch 5/100
3534/3534 - 172s - loss: 7.7243 - accuracy: 0.0170
Epoch 6/100
3534/3534 - 178s - loss: 7.3587 - accuracy: 0.0225
Epoch 7/100
3534/3534 - 189s - loss: 7.0305 - accuracy: 0.0327
Epoch 8/100
3534/3534 - 165s - loss: 6.7353 - accuracy: 0.0445
Epoch 9/100
3534/3534 - 152s - loss: 6.4321 - accuracy: 0.0572
Epoch 10/100
3534/3534 - 166s - loss: 6.1460 - accuracy: 0.0731
Epoch 11/100
3534/3534 - 167s - loss: 5.8910 - accuracy: 0.0883
Epoch 12/100
3534/3534 - 169s - loss: 5.6602 - accuracy: 0.1044
Epoch 13/100
3534/3534 - 164s - loss: 5.5746 - accuracy: 0.1091
Epoch 14/100
3534/3534 - 195s - loss: 5.3469 - accuracy: 0.1282
Epoch 15/100
3534/3534 - 177s - loss: 5.1402 - accuracy: 0.1469
Epoch 16/100
3534/3534 - 173s - loss: 4.9620 - ac

### Generator 만들기

In [96]:
def get_word(index, dic):
    
    for key,value in dic.items():
        if (value == index):
            return (key)

In [97]:
def RNN_novel_generator(model, tk, prompt, num):
    for n in range(num):
        splited = tk.texts_to_sequences([prompt])[0]
        padded = pad_sequences([splited], maxlen = max_len - 1, padding = "pre")
        predicted_idx = model.predict_classes(padded, verbose = 0)
        predicted_word = get_word(predicted_idx, tk.word_index)
        
        prompt = prompt + ' ' + predicted_word
    return (prompt)

In [100]:
print(RNN_novel_generator(model, tk, "좋아", 30));

좋아 내 목숨을 뭘 기실 이런 눈빛으로 말은 하고 있으려니까 그래서 시약 제조 그들을 모두 뼘은 정도를 뇌가 순수한 듯 그렇다면 내가 한 대 남자 나란히 있는 라고 차라리 아주 녀석이


### LSTM

In [ ]:
model2 = Sequential()
model2.add(Embedding(size, 10, input_length = max_len-1))
model2.add(LSTM(128))
model2.add(Dense(size, activation = 'softmax'))
model2.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model2.fit(x, y, epochs = 200, verbose = 2)

In [ ]:
print(RNN_novel_generator(model, tk, "말", 30));